name: e2e tests

on:
  pull_request:
    branches: [ "dev" ]
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * 1-5'
  # - cron: '0 */4 * * *'
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        # Docker Hub image
        image: postgres:17
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
          POSTGRES_DB: eap
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd="pg_isready -U app -d eap"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Checkout backend repo
        uses: actions/checkout@v5
        with:
          repository: Hacktivist-Hive-organization/eap-backend
          ref: dev
          path: backend

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install postgres client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Create schema
        run: |
          echo "Creating schema: ${{secrets.DATABASE_SCHEMA}} in db: ${{secrets.DATABASE_NAME}}"
          PGPASSWORD="${{secrets.DATABASE_PASSWORD}}" psql \
            -h localhost -p 5432 -U "${{secrets.DATABASE_USER}}" -d "${{secrets.DATABASE_NAME}}" \
            -c "CREATE SCHEMA IF NOT EXISTS ${{secrets.DATABASE_SCHEMA}};"

      - name: Create env file
        working-directory: backend
        run: |
          cat <<'EOF' > .env
          DATABASE_TYPE=postgresql
          DATABASE_HOST=127.0.0.1
          DATABASE_PORT=5432
          DATABASE_USER=${{secrets.DATABASE_USER}}
          DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}}
          DATABASE_NAME=${{secrets.DATABASE_NAME}}
          JWT_SECRET_KEY=${{secrets.JWT_SECRET_KEY}}
          DEVELOPMENT_ENVIRONMENT=True
          EMAIL_SERVICE=dummy
          MAIL_FROM_EMAIL=motopp.it31@gmail.com
          MAIL_FROM_NAME=Motopp
          MAILTRAP_USER=${{secrets.MAILTRAP_USER}}
          MAILTRAP_SMTP_PASSWORD=${{secrets.MAILTRAP_PASSWORD}}
          MAILTRAP_SMTP_HOST='sandbox.smtp.mailtrap.io'
          MAILTRAP_SMTP_PORT=2525
          MAILTRAP_USE_TLS=True
          MAILJET_API_KEY=${{secrets.MAILJET_API_KEY}}
          MAILJET_SECRET_KEY=${{secrets.MAILJET_SECRET_KEY}}
          EMAIL_VERIFICATION_REQUIRED=True
          ACCESS_TOKEN_EXPIRE_MINUTES=60
          PASSWORD_RESET_TOKEN_EXPIRE_MINUTES=15
          EMAIL_VERIFICATION_TOKEN_EXPIRE_MINUTES=30
          EOF

      - name: Install backend dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run alembic migrations
        working-directory: backend
        run: |
          alembic upgrade head

      - name: Start backend server
        working-directory: backend
        run: |
          nohup uvicorn app.main:app \
            --host 127.0.0.1 \
            --port 8000 \
            > ../backend.log 2>&1 &
        # capture logs and errors and run server in background

      - name: Checkout frontend repo
        uses: actions/checkout@v5
        with:
          repository: Hacktivist-Hive-organization/eap-frontend
          ref: dev
          path: frontend

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache-dependency-path: frontend/package-lock.json
          cache: 'npm'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Start frontend server
        working-directory: frontend
        env:
          VITE_API_URL: http://127.0.0.1:8000
        run: |
          nohup npm run dev -- --host 127.0.0.1 --port 5173 --strictPort > ../frontend.log 2>&1 &

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: List structure
        run: |
          ls -la

      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps

      - name: Run e2e tests
        run: pytest ./e2e_tests --html=artifacts/pytest-report.html --self-contained-html

      - name: Show backend log
        if: always()
        run: |
          echo "---- backend.log ----"
          cat backend.log || true
          echo "---------------------"

      - name: Show frontend log
        if: always()
        run: |
          echo "---- frontend.log ----"
          cat frontend.log || true
          echo "----------------------"

      - name: Upload Playwright traces
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v6
        with:
          name: artifacts
          path: ${{ github.workspace }}/artifacts
          if-no-files-found: warn
